name: Build MSIX

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: |
        dotnet restore TaskTrackerApp\TaskTrackerApp.csproj -r win-x64
        msbuild TaskTrackerApp.Packaging\TaskTrackerApp.Packaging.wapproj /t:Restore /p:Configuration=Release /p:Platform=x64 /p:RuntimeIdentifier=win-x64

    - name: Build MSIX bundle
      run: msbuild TaskTrackerApp.Packaging\TaskTrackerApp.Packaging.wapproj /p:Configuration=Release /p:Platform=x64 /p:UapAppxPackageBuildMode=StoreUpload /p:AppxBundle=Always /p:AppxPackageSigningEnabled=false /p:RuntimeIdentifier=win-x64

    - name: Sign MSIX bundle
      run: |
        $cert = New-SelfSignedCertificate -Type Custom -Subject "CN=00F61C64-FF38-455E-8D55-F7094707F364" -KeyUsage DigitalSignature -FriendlyName "TaskTracker Store Cert" -CertStoreLocation "Cert:\CurrentUser\My" -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3", "2.5.29.19={text}")
        $password = ConvertTo-SecureString -String "password" -Force -AsPlainText
        Export-PfxCertificate -Cert $cert -FilePath "TaskTrackerApp.Packaging\TaskTrackerCert.pfx" -Password $password
        Export-Certificate -Cert $cert -FilePath "TaskTrackerApp.Packaging\TaskTrackerCert.cer"
        
        $bundle = Get-ChildItem -Path TaskTrackerApp.Packaging\AppPackages\**\*.msixbundle
        $signtool = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\signtool.exe"
        
        & $signtool sign /fd SHA256 /a /f "TaskTrackerApp.Packaging\TaskTrackerCert.pfx" /p "password" $bundle.FullName

    - name: Upload MSIX
      uses: actions/upload-artifact@v4
      with:
        name: TaskTrackerApp-MSIX
        path: |
          TaskTrackerApp.Packaging\AppPackages\**\*.msixupload
          TaskTrackerApp.Packaging\AppPackages\**\*.msixbundle
          TaskTrackerApp.Packaging\TaskTrackerCert.cer
